version: '2'

services:
  frontend:
    container_name: todolist_frontend
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    networks:
      - app-network
    environment:
      - HOST=0.0.0.0
    restart: always
    ports:
      - "80:3000"
  backend:
    container_name: todolist_backend
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DBNAME: ${DB_DB}
    restart: always
  db:
    container_name: todolist_db
    image: mariadb:10.3
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./db/config:/etc/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DB}
